// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: event.sql

package db

import (
	"context"
	"database/sql"

	"github.com/jackc/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO webhook_events (
    id,
    event_id,
    event_type,
    status,
    payload,
    attempts,
    last_attempt_at,
    next_attempt_at,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, event_id, event_type, status, payload, attempts, last_attempt_at, next_attempt_at, error_message, created_at, updated_at
`

type CreateEventParams struct {
	ID            string
	EventID       string
	EventType     string
	Status        string
	Payload       pgtype.JSONB
	Attempts      int32
	LastAttemptAt sql.NullTime
	NextAttemptAt sql.NullTime
	ErrorMessage  sql.NullString
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.Status,
		arg.Payload,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.NextAttemptAt,
		arg.ErrorMessage,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM webhook_events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByEventID = `-- name: GetEventByEventID :one
SELECT id, event_id, event_type, status, payload, attempts, last_attempt_at, next_attempt_at, error_message, created_at, updated_at FROM webhook_events WHERE event_id = $1 LIMIT 1
`

func (q *Queries) GetEventByEventID(ctx context.Context, eventID string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getEventByEventID, eventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, event_id, event_type, status, payload, attempts, last_attempt_at, next_attempt_at, error_message, created_at, updated_at FROM webhook_events WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingEvents = `-- name: GetPendingEvents :many
SELECT id, event_id, event_type, status, payload, attempts, last_attempt_at, next_attempt_at, error_message, created_at, updated_at FROM webhook_events
WHERE status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= CURRENT_TIMESTAMP)
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, getPendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEvent
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE webhook_events
SET 
    status = $2,
    attempts = $3,
    last_attempt_at = $4,
    next_attempt_at = $5,
    error_message = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateEventStatusParams struct {
	ID            string
	Status        string
	Attempts      int32
	LastAttemptAt sql.NullTime
	NextAttemptAt sql.NullTime
	ErrorMessage  sql.NullString
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastAttemptAt,
		arg.NextAttemptAt,
		arg.ErrorMessage,
	)
	return err
}
