// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: fee.sql

package db

import (
	"context"

	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const getAllFeeRules = `-- name: GetAllFeeRules :many
SELECT 
    transaction_type,
    base_percentage,
    tier_overrides,
    peak_hours,
    fee_cap,
    fee_floor
FROM fee_rules
WHERE is_active = true
`

type GetAllFeeRulesRow struct {
	TransactionType string
	BasePercentage  decimal.Decimal
	TierOverrides   pgtype.JSONB
	PeakHours       pgtype.JSONB
	FeeCap          decimal.NullDecimal
	FeeFloor        decimal.NullDecimal
}

func (q *Queries) GetAllFeeRules(ctx context.Context) ([]GetAllFeeRulesRow, error) {
	rows, err := q.db.Query(ctx, getAllFeeRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeeRulesRow
	for rows.Next() {
		var i GetAllFeeRulesRow
		if err := rows.Scan(
			&i.TransactionType,
			&i.BasePercentage,
			&i.TierOverrides,
			&i.PeakHours,
			&i.FeeCap,
			&i.FeeFloor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeeRule = `-- name: GetFeeRule :one
SELECT 
    transaction_type,
    base_percentage,
    tier_overrides,
    peak_hours,
    fee_cap,
    fee_floor
FROM fee_rules
WHERE transaction_type = $1 AND is_active = true
LIMIT 1
`

type GetFeeRuleRow struct {
	TransactionType string
	BasePercentage  decimal.Decimal
	TierOverrides   pgtype.JSONB
	PeakHours       pgtype.JSONB
	FeeCap          decimal.NullDecimal
	FeeFloor        decimal.NullDecimal
}

func (q *Queries) GetFeeRule(ctx context.Context, transactionType string) (GetFeeRuleRow, error) {
	row := q.db.QueryRow(ctx, getFeeRule, transactionType)
	var i GetFeeRuleRow
	err := row.Scan(
		&i.TransactionType,
		&i.BasePercentage,
		&i.TierOverrides,
		&i.PeakHours,
		&i.FeeCap,
		&i.FeeFloor,
	)
	return i, err
}
