// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: login.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, phone, tier, password, status, created_at, updated_at, last_login
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Tier,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT id, name, email, phone, tier, password, status, created_at, updated_at, last_login
FROM users
WHERE phone = $1
`

func (q *Queries) FindUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Tier,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getBalanceByUserID = `-- name: GetBalanceByUserID :one
SELECT balance
FROM wallets
WHERE user_id = $1
`

func (q *Queries) GetBalanceByUserID(ctx context.Context, userID string) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getBalanceByUserID, userID)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, user_id, provider, account_number, amount, fee, currency, due_date, status, transaction_id, metadata, created_at, updated_at FROM bills WHERE id = $1
`

func (q *Queries) GetBillByID(ctx context.Context, id string) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByID, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountNumber,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.TransactionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTierConfig = `-- name: GetTierConfig :one
SELECT tier, name, monthly_fee, max_transactions, max_amount, features, created_at, updated_at FROM tier_configs WHERE tier = $1
`

func (q *Queries) GetTierConfig(ctx context.Context, tier string) (TierConfig, error) {
	row := q.db.QueryRow(ctx, getTierConfig, tier)
	var i TierConfig
	err := row.Scan(
		&i.Tier,
		&i.Name,
		&i.MonthlyFee,
		&i.MaxTransactions,
		&i.MaxAmount,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, tier, password, status, created_at, updated_at, last_login FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Tier,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateBillStatus = `-- name: UpdateBillStatus :exec
UPDATE bills 
SET status = $2, 
    updated_at = NOW()
WHERE id = $1
`

type UpdateBillStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateBillStatus(ctx context.Context, arg UpdateBillStatusParams) error {
	_, err := q.db.Exec(ctx, updateBillStatus, arg.ID, arg.Status)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateTierConfig = `-- name: UpdateTierConfig :exec
UPDATE tier_configs
SET 
    name = COALESCE($2, name),
    monthly_fee = COALESCE($3, monthly_fee),
    max_transactions = COALESCE($4, max_transactions),
    max_amount = COALESCE($5, max_amount),
    features = COALESCE($6, features),
    updated_at = NOW()
WHERE tier = $1
`

type UpdateTierConfigParams struct {
	Tier            string
	Name            string
	MonthlyFee      decimal.Decimal
	MaxTransactions int32
	MaxAmount       decimal.Decimal
	Features        pgtype.JSONB
}

func (q *Queries) UpdateTierConfig(ctx context.Context, arg UpdateTierConfigParams) error {
	_, err := q.db.Exec(ctx, updateTierConfig,
		arg.Tier,
		arg.Name,
		arg.MonthlyFee,
		arg.MaxTransactions,
		arg.MaxAmount,
		arg.Features,
	)
	return err
}

const userRegister = `-- name: UserRegister :one
INSERT INTO users (
    name,
    email,
    phone,
    password,
    tier,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, email, phone, tier, status, created_at, updated_at
`

type UserRegisterParams struct {
	Name     string
	Email    string
	Phone    sql.NullString
	Password string
	Tier     string
	Status   string
}

type UserRegisterRow struct {
	ID        string
	Name      string
	Email     string
	Phone     sql.NullString
	Tier      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UserRegister(ctx context.Context, arg UserRegisterParams) (UserRegisterRow, error) {
	row := q.db.QueryRow(ctx, userRegister,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Tier,
		arg.Status,
	)
	var i UserRegisterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Tier,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
