// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

type Bill struct {
	ID            string
	UserID        string
	Provider      string
	AccountNumber string
	Amount        decimal.Decimal
	Fee           decimal.Decimal
	Currency      string
	DueDate       sql.NullTime
	Status        string
	TransactionID sql.NullString
	Metadata      pgtype.JSONB
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type FeeRule struct {
	ID              int32
	TransactionType string
	BasePercentage  decimal.Decimal
	TierOverrides   pgtype.JSONB
	PeakHours       pgtype.JSONB
	FeeCap          decimal.NullDecimal
	FeeFloor        decimal.NullDecimal
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SessionLog struct {
	ID        int32
	UserID    string
	SessionID string
	IpAddress sql.NullString
	UserAgent sql.NullString
	LoginAt   time.Time
	LogoutAt  sql.NullTime
	ExpiredAt sql.NullTime
	Status    string
}

type TierConfig struct {
	Tier            string
	Name            string
	MonthlyFee      decimal.Decimal
	MaxTransactions int32
	MaxAmount       decimal.Decimal
	Features        pgtype.JSONB
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Transaction struct {
	ID              string
	UserID          string
	WalletID        string
	Amount          decimal.Decimal
	Fee             decimal.Decimal
	Currency        string
	TransactionType string
	Description     string
	Reference       uuid.UUID
	Status          string
	Metadata        pgtype.JSONB
	UserTier        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID        string
	Name      string
	Email     string
	Phone     sql.NullString
	Tier      string
	Password  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin sql.NullTime
}

type Wallet struct {
	ID        string
	UserID    string
	Balance   decimal.Decimal
	Currency  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type WebhookEvent struct {
	ID            string
	EventID       string
	EventType     string
	Status        string
	Payload       pgtype.JSONB
	Attempts      int32
	LastAttemptAt sql.NullTime
	NextAttemptAt sql.NullTime
	ErrorMessage  sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
