// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    wallet_id,
    amount,
    transaction_type,
    description,
    reference,
    status,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, wallet_id, amount, fee, currency, transaction_type, description, reference, status, metadata, user_tier, created_at, updated_at
`

type CreateTransactionParams struct {
	WalletID        string
	Amount          decimal.Decimal
	TransactionType string
	Description     string
	Reference       uuid.UUID
	Status          string
	Metadata        pgtype.JSONB
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.Reference,
		arg.Status,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.TransactionType,
		&i.Description,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.UserTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, wallet_id, amount, fee, currency, transaction_type, description, reference, status, metadata, user_tier, created_at, updated_at FROM transactions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.TransactionType,
		&i.Description,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.UserTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, user_id, wallet_id, amount, fee, currency, transaction_type, description, reference, status, metadata, user_tier, created_at, updated_at FROM transactions WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetTransactionByReference(ctx context.Context, reference uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.TransactionType,
		&i.Description,
		&i.Reference,
		&i.Status,
		&i.Metadata,
		&i.UserTier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, user_id, wallet_id, amount, fee, currency, transaction_type, description, reference, status, metadata, user_tier, created_at, updated_at FROM transactions
WHERE wallet_id = $1 AND transaction_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByTypeParams struct {
	WalletID        string
	TransactionType string
	Limit           int32
	Offset          int32
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByType,
		arg.WalletID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.Amount,
			&i.Fee,
			&i.Currency,
			&i.TransactionType,
			&i.Description,
			&i.Reference,
			&i.Status,
			&i.Metadata,
			&i.UserTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, user_id, wallet_id, amount, fee, currency, transaction_type, description, reference, status, metadata, user_tier, created_at, updated_at FROM transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.Amount,
			&i.Fee,
			&i.Currency,
			&i.TransactionType,
			&i.Description,
			&i.Reference,
			&i.Status,
			&i.Metadata,
			&i.UserTier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionsByType = `-- name: SumTransactionsByType :one
SELECT COALESCE(SUM(amount), 0) FROM transactions
WHERE wallet_id = $1 AND transaction_type = $2 AND status = 'completed'
`

type SumTransactionsByTypeParams struct {
	WalletID        string
	TransactionType string
}

func (q *Queries) SumTransactionsByType(ctx context.Context, arg SumTransactionsByTypeParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumTransactionsByType, arg.WalletID, arg.TransactionType)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status)
	return err
}
