// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: wallet.sql

package db

import (
	"context"
	"database/sql"

	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, currency)
VALUES ($1, $2)
RETURNING id, user_id, balance, currency, status, created_at, updated_at
`

type CreateWalletParams struct {
	UserID   string
	Currency string
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillByReferenceID = `-- name: GetBillByReferenceID :one
SELECT id, user_id, provider, account_number, amount, fee, currency, due_date, status, transaction_id, metadata, created_at, updated_at FROM bills
WHERE id = $1
`

func (q *Queries) GetBillByReferenceID(ctx context.Context, id string) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByReferenceID, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountNumber,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.TransactionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, balance, currency, status, created_at, updated_at FROM wallets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWallet(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUser = `-- name: GetWalletByUser :one
SELECT id, user_id, balance, currency, status, created_at, updated_at FROM wallets WHERE user_id = $1 AND currency = $2 LIMIT 1
`

type GetWalletByUserParams struct {
	UserID   string
	Currency string
}

func (q *Queries) GetWalletByUser(ctx context.Context, arg GetWalletByUserParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUser, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWallets = `-- name: ListWallets :many
SELECT id, user_id, balance, currency, status, created_at, updated_at FROM wallets
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWallets(ctx context.Context, userID string) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerBill = `-- name: RegisterBill :one
INSERT INTO bills (
    id,
    user_id,
    provider,
    account_number,
    amount,
    fee,
    currency,
    due_date,
    status,
    transaction_id,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, provider, account_number, amount, fee, currency, due_date, status, transaction_id, metadata, created_at, updated_at
`

type RegisterBillParams struct {
	ID            string
	UserID        string
	Provider      string
	AccountNumber string
	Amount        decimal.Decimal
	Fee           decimal.Decimal
	Currency      string
	DueDate       sql.NullTime
	Status        string
	TransactionID sql.NullString
	Metadata      pgtype.JSONB
}

func (q *Queries) RegisterBill(ctx context.Context, arg RegisterBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, registerBill,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AccountNumber,
		arg.Amount,
		arg.Fee,
		arg.Currency,
		arg.DueDate,
		arg.Status,
		arg.TransactionID,
		arg.Metadata,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountNumber,
		&i.Amount,
		&i.Fee,
		&i.Currency,
		&i.DueDate,
		&i.Status,
		&i.TransactionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets
SET 
    balance = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateWalletBalanceParams struct {
	ID      string
	Balance decimal.Decimal
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.ID, arg.Balance)
	return err
}
