debug: true
dev: true
server:
  host:
  port: 8000
  timeout: 30s
  read_header_timeout: 30s
  retry:
    initial_interval: 2s
    randomization_factor: 0.2
    multiplier: 5
    max_interval: 24h
    max_elapsed_time: 168h
swagger: 
  schemes:
    - http
  host: localhost:8000
database:
  conn-string: postgres://root:@localhost:26257/digital-wallet?sslmode=disable&pool_max_conns=10
redis:
  url: redis://localhost:6379
  expire_duration: 60000s
migration:
  active: true
  seed_active: true
  path: ./db/migrations/up